version: '3.8'

services:
  vibe-coder-app:
    build: .
    container_name: vibe-coder-rules-generator
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/var/log/nginx
    networks:
      - vibe-coder-network

networks:
  vibe-coder-network:
    driver: bridge

volumes:
  logs: 